//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  S:\lian\Application\fk.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: pettycc
//              Version: NX 2306
//              Date: 07-08-2026  (Format: mm-dd-yyyy)
//              Time: 14:46
//
//==============================================================================

#ifndef FK_H_INCLUDED
#define FK_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <uf_defs.h>
#include <uf_ui_types.h>
#include <iostream>
#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include <NXOpen/BlockStyler_Button.hxx>
#include <NXOpen/BlockStyler_Group.hxx>
#include <NXOpen/BlockStyler_CompositeBlock.hxx>

#include "AsmCreationToolUI_ReplaceComponentBase.hpp"
//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

class DllExport fk
{
    // class members
public:
    static Session *theSession;
    static UI *theUI;
    fk();
    ~fk();
    NXOpen::BlockStyler::BlockDialog::DialogResponse Launch();
    
    //----------------------- BlockStyler Callback Prototypes ---------------------
    // The following member function prototypes define the callbacks 
    // specified in your BlockStyler dialog.  The empty implementation
    // of these prototypes is provided in the fk.cpp file. 
    // You are REQUIRED to write the implementation for these functions.
    //------------------------------------------------------------------------------
    void initialize_cb();
    void dialogShown_cb();
    int apply_cb();
    int ok_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    PropertyList* GetBlockProperties(const char *blockID);
    
private:
    const char* theDlxFileName;
    NXOpen::BlockStyler::BlockDialog* theDialog;
    NXOpen::BlockStyler::Button* button01;// Block type: Button
    NXOpen::BlockStyler::Group* group0;
    AsmCreationToolUI_ReplaceComponentBase* asmCreationToolUI_ReplaceComponentBase0;
    NXOpen::BlockStyler::Button* button0;// Block type: Button
    
};
#endif //FK_H_INCLUDED
