//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  D:\nxfile\Application\BlockStyler777.cpp
//
//        This file was generated by the NX Block UI Styler
//        Created by: Az202
//              Version: NX 2306
//              Date: 07-15-2026  (Format: mm-dd-yyyy)
//              Time: 10:55 (Format: hh-mm)
//
//==============================================================================
//  Business logic: Point-to-Point Move & Copy  (pure NXOpen, no UFUN)
//==============================================================================

#include "BlockStyler777.hpp"
#include <NXOpen/Features_BaseFeatureCollection.hxx>
#include <NXOpen/SelectNXObjectList.hxx>
#include <NXOpen/DirectionCollection.hxx>
#include <NXOpen/AxisCollection.hxx>
#include <cmath>
#include <set>
#include <string>
#include <sstream>
#include <stdexcept>

using namespace NXOpen;
using namespace NXOpen::BlockStyler;

Session *(BlockStyler777::theSession) = NULL;
UI *(BlockStyler777::theUI) = NULL;

BlockStyler777::BlockStyler777()
{
    group = NULL; movebutton = NULL; copybutton = NULL;
    group1 = NULL; selection0 = NULL; group2 = NULL;
    point0 = NULL; enum01 = NULL; group3 = NULL;
    point01 = NULL; enum0 = NULL;
    try {
        BlockStyler777::theSession = NXOpen::Session::GetSession();
        BlockStyler777::theUI = UI::GetUI();
        theDlxFileName = "777.dlx";
        theUserDefinedUIBlock = BlockStyler777::theUI->CreateDialog(theDlxFileName);
        theUserDefinedUIBlock->AddUpdateHandler(make_callback(this, &BlockStyler777::update_cb));
        theUserDefinedUIBlock->AddInitializeHandler(make_callback(this, &BlockStyler777::initialize_cb));
        theUserDefinedUIBlock->AddDialogShownHandler(make_callback(this, &BlockStyler777::dialogShown_cb));
        // Register Apply and OK handlers so the dialog's OK/Apply buttons work
        theUserDefinedUIBlock->AddApplyHandler(make_callback(this, &BlockStyler777::apply_cb));
        theUserDefinedUIBlock->AddOkHandler(make_callback(this, &BlockStyler777::ok_cb));
    } catch(exception&) { throw; }
}

BlockStyler777::~BlockStyler777()
{
    if (theUserDefinedUIBlock != NULL) { delete theUserDefinedUIBlock; theUserDefinedUIBlock = NULL; }
}

void BlockStyler777::initialize_cb()
{
    try {
        group = dynamic_cast<NXOpen::BlockStyler::Group*>(theUserDefinedUIBlock->TopBlock()->FindBlock("group"));
        movebutton = dynamic_cast<NXOpen::BlockStyler::Button*>(theUserDefinedUIBlock->TopBlock()->FindBlock("movebutton"));
        copybutton = dynamic_cast<NXOpen::BlockStyler::Button*>(theUserDefinedUIBlock->TopBlock()->FindBlock("copybutton"));
        group1 = dynamic_cast<NXOpen::BlockStyler::Group*>(theUserDefinedUIBlock->TopBlock()->FindBlock("group1"));
        selection0 = dynamic_cast<NXOpen::BlockStyler::SelectObject*>(theUserDefinedUIBlock->TopBlock()->FindBlock("selection0"));
        group2 = dynamic_cast<NXOpen::BlockStyler::Group*>(theUserDefinedUIBlock->TopBlock()->FindBlock("group2"));
        point0 = dynamic_cast<NXOpen::BlockStyler::SpecifyPoint*>(theUserDefinedUIBlock->TopBlock()->FindBlock("point0"));
        enum01 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theUserDefinedUIBlock->TopBlock()->FindBlock("enum01"));
        group3 = dynamic_cast<NXOpen::BlockStyler::Group*>(theUserDefinedUIBlock->TopBlock()->FindBlock("group3"));
        point01 = dynamic_cast<NXOpen::BlockStyler::SpecifyPoint*>(theUserDefinedUIBlock->TopBlock()->FindBlock("point01"));
        enum0 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theUserDefinedUIBlock->TopBlock()->FindBlock("enum0"));
    } catch(exception& ex) {
        BlockStyler777::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//------------------------------------------------------------------------------


void BlockStyler777::dialogShown_cb()
{
    try {
        UpdateUI();
    } catch(exception& ex) {
        BlockStyler777::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}
int BlockStyler777::update_cb(NXOpen::BlockStyler::UIBlock* block)
{
    try {
        if (block == movebutton) { ExecuteOperation(false); }
        else if (block == copybutton) { ExecuteOperation(true); }
        else if (block == enum01) { UpdateUI(); }
        else if (block == enum0) { UpdateUI(); }
    } catch(exception& ex) {
        BlockStyler777::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//==============================================================================
// Helper methods  (pure NXOpen, no UFUN, no BoundingBox)
//==============================================================================

int BlockStyler777::GetPointMode()
{
    PropertyList* props = GetBlockProperties("enum01");
    return (props != nullptr) ? props->GetEnum("Value") : 0;
}

int BlockStyler777::GetEndMode()
{
    PropertyList* props = GetBlockProperties("enum0");
    return (props != nullptr) ? props->GetEnum("Value") : 0;
}

PropertyList* BlockStyler777::GetBlockProperties(const char* blockID)
{
    return theUserDefinedUIBlock->GetBlockProperties(blockID);
}

std::vector<NXObject*> BlockStyler777::GetSelectedObjects()
{
    std::vector<NXObject*> result;
    if (selection0 != nullptr) {
        std::vector<TaggedObject*> taggedObjs = selection0->GetSelectedObjects();
        for (auto obj : taggedObjs) {
            NXObject* nxObj = dynamic_cast<NXObject*>(obj);
            if (nxObj != nullptr) result.push_back(nxObj);
        }
    }
    return result;
}

// Resolve start point. All modes fall back to point0 since NXOpen
// has no GetBoundingBox / Evaluate methods and UFUN is prohibited.
Point3d BlockStyler777::ResolveStartPoint(TaggedObject* primaryObject)
{
    int sm = GetPointMode();
    if (sm == 4) {
        return (point0 != nullptr) ? point0->Point() : Point3d(0.0,0.0,0.0);
    }
    // 非自由模式: 从选中对象获取体
    Body* body = dynamic_cast<Body*>(primaryObject);
    if (body == nullptr) {
        // 选中的可能是特征，从特征获取体
        auto feat = dynamic_cast<NXOpen::Features::Feature*>(primaryObject);
        if (feat != nullptr) {
            std::vector<Body*> bodies = feat->GetBodies();
            if (!bodies.empty()) body = bodies.front();
        }
    }
    if (body != nullptr) {
        double cx=0, cy=0, cz=0; int count=0;
        std::vector<NXOpen::Edge*> edges = body->GetEdges();
        for (auto edge : edges) {
            Point3d v1, v2;
            edge->GetVertices(&v1, &v2);
            cx += v1.X + v2.X; cy += v1.Y + v2.Y; cz += v1.Z + v2.Z;
            count += 2;
        }
        if (count > 0) {
            Point3d center(cx/count, cy/count, cz/count);
            if (sm == 0) return Point3d(center.X, center.Y, center.Z + 50.0);
            if (sm == 2) return Point3d(center.X, center.Y, center.Z - 50.0);
            return center;
        }
    }
    return (point0 != nullptr) ? point0->Point() : Point3d(0.0,0.0,0.0);
}

Point3d BlockStyler777::ResolveEndPoint(TaggedObject* primaryObject, const Point3d& startPoint)
{
    int mode = GetEndMode();
    // Get the user-clicked end point as base for calculated modes
    Point3d clickPt = (point01 != nullptr) ? point01->Point() : Point3d(0.0,0.0,0.0);
    switch (mode) {
    case 0: return Point3d(0.0, 0.0, 0.0);
    case 1: return clickPt;
    case 2: return Point3d(clickPt.X, clickPt.Y, 0.0);
    case 3: {
        Session* s = Session::GetSession();
        Part* wp = s->Parts()->Work();
        if (wp && wp->WCS()) return wp->WCS()->Origin();
        return Point3d(0.0, 0.0, 0.0);
    }
    case 4: return Point3d(0.0, clickPt.Y, clickPt.Z);
    case 5: return clickPt;
    case 6: return clickPt;
    case 7: return clickPt;
    default: throw std::runtime_error("unknown end mode");
    }
}
bool BlockStyler777::ValidateParameters()
{
    if (GetSelectedObjects().empty()) {
        theUI->NXMessageBox()->Show("Hint", NXOpen::NXMessageBox::DialogTypeInformation, "Select objects first!");
        return false;
    }
    return true;
}

void BlockStyler777::UpdateUI() { }

void BlockStyler777::ExecuteOperation(bool isCopy)
{
    if (!ValidateParameters()) return;
    Session* s = Session::GetSession();
    Part* wp = s->Parts()->Work();
    NXString markName = isCopy ? "777 Copy" : "777 Move";
    Session::UndoMarkId markId = s->SetUndoMark(Session::MarkVisibilityVisible, markName);

    try {
        int mode = GetPointMode();
        if (mode == 5) ExecuteRotation(isCopy);
        else ExecuteTranslation(isCopy);
        s->UpdateManager()->DoUpdate(markId);
    } catch (const std::exception& ex) {
        s->UndoToMark(markId, NULL);
        theUI->NXMessageBox()->Show("Error", NXOpen::NXMessageBox::DialogTypeError, ex.what());
        return;
    }
}

// Translation: OptionsPointToPoint + SetFromPoint/SetToPoint
void BlockStyler777::ExecuteTranslation(bool isCopy)
{
    Session* s = Session::GetSession();
    Part* wp = s->Parts()->Work();
    auto sel = GetSelectedObjects();
    TaggedObject* primary = sel.empty() ? nullptr : sel.front();

    Point3d startPt = ResolveStartPoint(primary);
    Point3d endPt = ResolveEndPoint(primary, startPt);

    double dx = endPt.X - startPt.X, dy = endPt.Y - startPt.Y, dz = endPt.Z - startPt.Z;
    double dist = std::sqrt(dx*dx + dy*dy + dz*dz);
    if (dist < 1.0e-9) {
        theUI->NXMessageBox()->Show("Hint", NXOpen::NXMessageBox::DialogTypeInformation,
            "Start and end points coincide, cannot move/copy by zero vector");
        return;
    }

    NXOpen::Features::MoveObjectBuilder* mb = wp->BaseFeatures()->CreateMoveObjectBuilder(nullptr);
    mb->SetMoveObjectResult(isCopy
        ? NXOpen::Features::MoveObjectBuilder::MoveObjectResultOptionsCopyOriginal
        : NXOpen::Features::MoveObjectBuilder::MoveObjectResultOptionsMoveOriginal);
        // Add objects individually for reliable transfer
        auto moveList = mb->ObjectToMoveObject();
        for (auto obj : sel) moveList->Add(obj);

    NXOpen::GeometricUtilities::ModlMotion* motion = mb->TransformMotion();
    motion->SetOption(NXOpen::GeometricUtilities::ModlMotion::OptionsPointToPoint);

    NXOpen::Point* fromPt = wp->Points()->CreatePoint(startPt);
    NXOpen::Point* toPt = wp->Points()->CreatePoint(endPt);
    motion->SetFromPoint(fromPt);
    motion->SetToPoint(toPt);

    mb->Commit();
    mb->Destroy();
    s->UpdateManager()->AddToDeleteList(fromPt);
    s->UpdateManager()->AddToDeleteList(toPt);
}

// Rotation: OptionsAngle + SetAngularAxis + Angle
void BlockStyler777::ExecuteRotation(bool isCopy)
{
    Session* s = Session::GetSession();
    Part* wp = s->Parts()->Work();
    auto sel = GetSelectedObjects();
    Point3d rotPt = (point0 != nullptr) ? point0->Point() : Point3d(0,0,0);

    Vector3d axis(0,0,1);
    if (point01 != nullptr) {
        Point3d end = point01->Point();
        axis = Vector3d(end.X-rotPt.X, end.Y-rotPt.Y, end.Z-rotPt.Z);
        double len = std::sqrt(axis.X*axis.X + axis.Y*axis.Y + axis.Z*axis.Z);
        if (len > 1e-9) { axis.X/=len; axis.Y/=len; axis.Z/=len; }
    }

    static const double angles[] = {15,30,45,60,90,120,180};
    int am = GetEndMode();
    double deg = (am>=0 && am<=6) ? angles[am] : 90.0;
    double rad = deg * 3.14159265358979323846 / 180.0;

    NXOpen::Features::MoveObjectBuilder* mb = wp->BaseFeatures()->CreateMoveObjectBuilder(nullptr);
    mb->SetMoveObjectResult(isCopy
        ? NXOpen::Features::MoveObjectBuilder::MoveObjectResultOptionsCopyOriginal
        : NXOpen::Features::MoveObjectBuilder::MoveObjectResultOptionsMoveOriginal);
        // Add objects individually for reliable transfer
        auto moveList = mb->ObjectToMoveObject();
        for (auto obj : sel) moveList->Add(obj);

    NXOpen::Point* cp = wp->Points()->CreatePoint(rotPt);
    NXOpen::Direction* dir = wp->Directions()->CreateDirection(rotPt, axis, NXOpen::SmartObject::UpdateOptionWithinModeling);
    NXOpen::Axis* ax = wp->Axes()->CreateAxis(cp, dir, NXOpen::SmartObject::UpdateOptionWithinModeling);

    NXOpen::GeometricUtilities::ModlMotion* motion = mb->TransformMotion();
    motion->SetOption(NXOpen::GeometricUtilities::ModlMotion::OptionsAngle);
    motion->SetAngularAxis(ax);
    motion->Angle()->SetValue(rad);

    mb->Commit();
    mb->Destroy();
    s->UpdateManager()->AddToDeleteList(cp);
}

//==============================================================================
// NX Open entry points (standalone dialog launch)
//==============================================================================

NXOpen::BlockStyler::BlockDialog::DialogResponse BlockStyler777::Launch()
{
    NXOpen::BlockStyler::BlockDialog::DialogResponse resp =
        NXOpen::BlockStyler::BlockDialog::DialogResponse::DialogResponseInvalid;
    try
    {
        resp = theUserDefinedUIBlock->Launch();
    }
    catch(exception& ex)
    {
        BlockStyler777::theUI->NXMessageBox()->Show("Block Styler",
            NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return resp;
}

extern "C" DllExport void ufusr(char *param, int *retcod, int param_len)
{
    BlockStyler777 *theDlg = NULL;
    try
    {
        theDlg = new BlockStyler777();
        theDlg->Launch();
    }
    catch(exception& ex)
    {
        BlockStyler777::theUI->NXMessageBox()->Show("Block Styler",
            NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    if (theDlg != NULL) { delete theDlg; theDlg = NULL; }
}

//------------------------------------------------------------------------------


extern "C" DllExport int ufusr_ask_unload()
{
    return (int)Session::LibraryUnloadOptionImmediately;
}

extern "C" DllExport void ufusr_cleanup(void)
{
}

BlockStyler777* BlockStyler777::RegisterUserDefinedUIBlock(NXOpen::BlockStyler::BlockDialog* parentDialog, const char* blockID)

//------------------------------------------------------------------------------
//------------------------------------------------------------------------------

{
    BlockStyler777* t = new BlockStyler777();
    parentDialog->RegisterUserDefinedUIBlock(t->theUserDefinedUIBlock, blockID);
    return t;
}

NXOpen::BlockStyler::CompositeBlock* BlockStyler777::GetTopBlock()
{
    return (theUserDefinedUIBlock != NULL) ? theUserDefinedUIBlock->TopBlock() : NULL;

//------------------------------------------------------------------------------

}

//------------------------------------------------------------------------------


//------------------------------------------------------------------------------


//------------------------------------------------------------------------------
int BlockStyler777::apply_cb()
{
    ExecuteOperation(false);
    return 0;
}

int BlockStyler777::ok_cb()
{
    ExecuteOperation(false);
    return 0;
}
