//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  S:\visiable\coaicad\Application\dotmove_copy.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: pettycc
//              Version: NX 2306
//              Date: 07-16-2026  (Format: mm-dd-yyyy)
//              Time: 10:07
//
//==============================================================================

#ifndef DOTMOVE_COPY_H_INCLUDED
#define DOTMOVE_COPY_H_INCLUDED

#include <uf_defs.h>
#include <uf_ui_types.h>
#include <iostream>
#include <vector>
#include <math.h>
#include <string>
#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include <NXOpen/BlockStyler_Group.hxx>
#include <NXOpen/BlockStyler_Button.hxx>
#include <NXOpen/BlockStyler_SelectObject.hxx>
#include <NXOpen/BlockStyler_SpecifyPoint.hxx>
#include <NXOpen/BlockStyler_Enumeration.hxx>
#include <NXOpen/NXObject.hxx>
#include <NXOpen/Part.hxx>
#include <NXOpen/PartCollection.hxx>
#include <NXOpen/BasePart.hxx>
#include <NXOpen/Update.hxx>
#include <NXOpen/SelectNXObjectList.hxx>
#include <NXOpen/Features_BaseFeatureCollection.hxx>
#include <NXOpen/Features_MoveObjectBuilder.hxx>
#include <NXOpen/GeometricUtilities_ModlMotion.hxx>
#include <NXOpen/ugmath.hxx>
#include <NXOpen/WCS.hxx>

using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

// Enum types matching the dropdown values (0 = first item = manual)
enum StartPointType { START_MANUAL = 0, START_BODY_TOP = 1, START_BODY_CENTER = 2, START_BODY_BOTTOM = 3, START_FACE_CENTER = 4 };
enum EndPointType   { END_MANUAL = 0, END_ABS_ORIGIN = 1, END_ZO = 2, END_WCS_ORIGIN = 3, END_XO = 4, END_BODY_CENTER = 5, END_YO = 6 };

class DllExport dotmove_copy
{
public:
    static Session *theSession;
    static UI *theUI;
    dotmove_copy();
    ~dotmove_copy();
    void Launch();

    void initialize_cb();
    void dialogShown_cb();
    int apply_cb();
    int ok_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    PropertyList* GetBlockProperties(const char *blockID);

private:
    const char* theDlxFileName;
    NXOpen::BlockStyler::BlockDialog* theDialog;
    NXOpen::BlockStyler::Group* group0;
    NXOpen::BlockStyler::Button* move_button;
    NXOpen::BlockStyler::Button* copy_button;
    NXOpen::BlockStyler::Group* group1;
    NXOpen::BlockStyler::SelectObject* selection0;
    NXOpen::BlockStyler::Group* group2;
    NXOpen::BlockStyler::SpecifyPoint* startpoint;
    NXOpen::BlockStyler::Enumeration* start_enum;
    NXOpen::BlockStyler::Group* group;
    NXOpen::BlockStyler::SpecifyPoint* endpoint;
    NXOpen::BlockStyler::Enumeration* end_enum;

    int m_actionMode; // 0=none, 1=move, 2=copy
    bool executeTransform();
};

#endif //DOTMOVE_COPY_H_INCLUDED



