//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  S:\visiable\coaicad\Application\dotmove_copy.cpp
//
//        This file was generated by the NX Block UI Styler
//        Created by: pettycc
//              Version: NX 2306
//              Date: 07-16-2026  (Format: mm-dd-yyyy)
//              Time: 10:07 (Format: hh-mm)
//
//==============================================================================

#include "dotmove_copy.hpp"
#include <NXOpen/BasePart.hxx>
#include <NXOpen/Update.hxx>
#include <uf_modl_utilities.h>

using namespace NXOpen;
using namespace NXOpen::BlockStyler;

Session *(dotmove_copy::theSession) = NULL;
UI *(dotmove_copy::theUI) = NULL;

dotmove_copy::dotmove_copy()
{
    try
    {
        dotmove_copy::theSession = NXOpen::Session::GetSession();
        dotmove_copy::theUI = UI::GetUI();
        theDlxFileName = "dotmove_copy.dlx";
        theDialog = dotmove_copy::theUI->CreateDialog(theDlxFileName);
        theDialog->AddApplyHandler(make_callback(this, &dotmove_copy::apply_cb));
        theDialog->AddOkHandler(make_callback(this, &dotmove_copy::ok_cb));
        theDialog->AddUpdateHandler(make_callback(this, &dotmove_copy::update_cb));
        theDialog->AddInitializeHandler(make_callback(this, &dotmove_copy::initialize_cb));
        theDialog->AddDialogShownHandler(make_callback(this, &dotmove_copy::dialogShown_cb));
    }
    catch(exception& ex)
    {
        throw;
    }
}

dotmove_copy::~dotmove_copy()
{
    if (theDialog != NULL)
    {
        delete theDialog;
        theDialog = NULL;
    }
}

extern "C" DllExport void ufusr(char *param, int *retcod, int param_len)
{
    dotmove_copy *thedotmove_copy = NULL;
    try
    {
        thedotmove_copy = new dotmove_copy();
        thedotmove_copy->Launch();
    }
    catch(exception& ex)
    {
        dotmove_copy::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    if(thedotmove_copy != NULL)
    {
        delete thedotmove_copy;
        thedotmove_copy = NULL;
    }
}

void dotmove_copy::Launch()
{
    try
    {
        theDialog->Show();
    }
    catch(exception& ex)
    {
        theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

void dotmove_copy::initialize_cb()
{
    try
    {
        m_actionMode = 0;
        group0 = (NXOpen::BlockStyler::Group*)theDialog->TopBlock()->FindBlock("group0");
        move_button = (NXOpen::BlockStyler::Button*)theDialog->TopBlock()->FindBlock("move_button");
        copy_button = (NXOpen::BlockStyler::Button*)theDialog->TopBlock()->FindBlock("copy_button");
        group1 = (NXOpen::BlockStyler::Group*)theDialog->TopBlock()->FindBlock("group1");
        selection0 = (NXOpen::BlockStyler::SelectObject*)theDialog->TopBlock()->FindBlock("selection0");
        group2 = (NXOpen::BlockStyler::Group*)theDialog->TopBlock()->FindBlock("group2");
        startpoint = (NXOpen::BlockStyler::SpecifyPoint*)theDialog->TopBlock()->FindBlock("startpoint");
        start_enum = (NXOpen::BlockStyler::Enumeration*)theDialog->TopBlock()->FindBlock("start_enum");
        group = (NXOpen::BlockStyler::Group*)theDialog->TopBlock()->FindBlock("group");
        endpoint = (NXOpen::BlockStyler::SpecifyPoint*)theDialog->TopBlock()->FindBlock("endpoint");
        end_enum = (NXOpen::BlockStyler::Enumeration*)theDialog->TopBlock()->FindBlock("end_enum");
    }
    catch(exception& ex)
    {
        theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

void dotmove_copy::dialogShown_cb()
{
    try
    {
    }
    catch(exception& ex)
    {
        theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
// Static helpers
//------------------------------------------------------------------------------

static bool HasPointValue(SpecifyPoint* sp)
{
    if (sp == NULL) return false;
    try
    {
        Point3d pt = sp->Point();
        return (fabs(pt.X) > 0.0001 || fabs(pt.Y) > 0.0001 || fabs(pt.Z) > 0.0001);
    }
    catch(...) { return false; }
}

static Point3d GetPointFromSp(SpecifyPoint* sp)
{
    Point3d pt = {0,0,0};
    if (sp == NULL) return pt;
    try { pt = sp->Point(); } catch(...) { }
    return pt;
}

static int GetEnumValue(Enumeration* enumCtrl)
{
    if (enumCtrl == NULL) return 0;
    try
    {
        PropertyList* props = enumCtrl->GetProperties();
        int val = props->GetEnum("Value");
        delete props;
        return val;
    }
    catch(...) { return 0; }
}

static Point3d GetWcsOrigin()
{
    Part* workPart = dotmove_copy::theSession->Parts()->Work();
    return workPart->WCS()->Origin();
}

//------------------------------------------------------------------------------
// Bounding box using UF_MODL_ask_bounding_box
//------------------------------------------------------------------------------
static bool GetBoundingBoxCenter(const std::vector<TaggedObject*>& objs, Point3d& center, double& halfZ)
{
    bool first = true;
    double xMin = 0, xMax = 0, yMin = 0, yMax = 0, zMin = 0, zMax = 0;

    for (TaggedObject* obj : objs)
    {
        double box[6];
        if (UF_MODL_ask_bounding_box(obj->Tag(), box) == 0)
        {
            if (first)
            {
                xMin = box[0]; yMin = box[1]; zMin = box[2];
                xMax = box[3]; yMax = box[4]; zMax = box[5];
                first = false;
            }
            else
            {
                if (box[0] < xMin) xMin = box[0];
                if (box[1] < yMin) yMin = box[1];
                if (box[2] < zMin) zMin = box[2];
                if (box[3] > xMax) xMax = box[3];
                if (box[4] > yMax) yMax = box[4];
                if (box[5] > zMax) zMax = box[5];
            }
        }
    }

    if (first) return false;

    center.X = (xMin + xMax) / 2.0;
    center.Y = (yMin + yMax) / 2.0;
    center.Z = (zMin + zMax) / 2.0;
    halfZ = (zMax - zMin) / 2.0;
    return true;
}

//------------------------------------------------------------------------------
// Resolve start point from enumeration and optional specify point
//------------------------------------------------------------------------------
static Point3d ResolveStartPoint(StartPointType type, SpecifyPoint* sp,
    const std::vector<TaggedObject*>& selObjs, UI* theUI, Session* theSession)
{
    if (type == START_MANUAL)
    {
        if (!HasPointValue(sp))
        {
            theUI->NXMessageBox()->Show("dotmove_copy", NXOpen::NXMessageBox::DialogTypeError,
                "Please select a start point in the graphics window.");
            return Point3d{0,0,0};
        }
        return GetPointFromSp(sp);
    }

    Point3d center = {0,0,0};
    double halfZ = 0;
    if (!GetBoundingBoxCenter(selObjs, center, halfZ))
    {
        theUI->NXMessageBox()->Show("dotmove_copy", NXOpen::NXMessageBox::DialogTypeError,
            "Please select objects for bounding-box calculation.");
        return Point3d{0,0,0};
    }

    switch (type)
    {
    case START_BODY_TOP:      return Point3d{center.X, center.Y, center.Z + halfZ};
    case START_BODY_BOTTOM:   return Point3d{center.X, center.Y, center.Z - halfZ};
    default:                  return center; // BODY_CENTER, FACE_CENTER
    }
}

//------------------------------------------------------------------------------
// Resolve end point from enumeration and optional specify point
//------------------------------------------------------------------------------
static Point3d ResolveEndPoint(EndPointType type, SpecifyPoint* sp,
    const std::vector<TaggedObject*>& selObjs, UI* theUI, Session* theSession)
{
    if (type == END_MANUAL)
    {
        if (!HasPointValue(sp))
        {
            theUI->NXMessageBox()->Show("dotmove_copy", NXOpen::NXMessageBox::DialogTypeError,
                "Please select an end point in the graphics window.");
            return Point3d{0,0,0};
        }
        return GetPointFromSp(sp);
    }

    switch (type)
    {
    case END_ABS_ORIGIN:  return Point3d{0,0,0};
    case END_WCS_ORIGIN:  return GetWcsOrigin();
    case END_ZO:          return Point3d{0,0,1};
    case END_XO:          return Point3d{1,0,0};
    case END_YO:          return Point3d{0,1,0};
    default:              break;
    }

    Point3d center = {0,0,0};
    double halfZ = 0;
    if (!GetBoundingBoxCenter(selObjs, center, halfZ))
    {
        theUI->NXMessageBox()->Show("dotmove_copy", NXOpen::NXMessageBox::DialogTypeError,
            "Please select objects for bounding-box calculation.");
        return Point3d{0,0,0};
    }
    return center; // END_BODY_CENTER
}

//------------------------------------------------------------------------------
// Execute the move or copy using MoveObjectBuilder
//------------------------------------------------------------------------------
bool dotmove_copy::executeTransform()
{
    StartPointType startType = (StartPointType)GetEnumValue(start_enum);
    EndPointType endType = (EndPointType)GetEnumValue(end_enum);

    std::vector<TaggedObject*> selObjs;
    try
    {
        selObjs = selection0->GetSelectedObjects();
    }
    catch(...) { }

    if (selObjs.empty())
    {
        theUI->NXMessageBox()->Show("dotmove_copy", NXOpen::NXMessageBox::DialogTypeError,
            "Please select objects first!");
        return false;
    }

    Point3d startPt = ResolveStartPoint(startType, startpoint, selObjs, theUI, theSession);
    Point3d endPt   = ResolveEndPoint(endType,   endpoint,   selObjs, theUI, theSession);

    Vector3d vec;
    vec.X = endPt.X - startPt.X;
    vec.Y = endPt.Y - startPt.Y;
    vec.Z = endPt.Z - startPt.Z;

    if (fabs(vec.X) < 0.0001 && fabs(vec.Y) < 0.0001 && fabs(vec.Z) < 0.0001)
    {
        theUI->NXMessageBox()->Show("dotmove_copy", NXOpen::NXMessageBox::DialogTypeError,
            "Start point and end point are identical!");
        return false;
    }

    Part* workPart = theSession->Parts()->Work();
    Features::MoveObjectBuilder* moveBuilder = workPart->BaseFeatures()->CreateMoveObjectBuilder(NULL);

    for (TaggedObject* obj : selObjs)
    {
        NXObject* nxObj = dynamic_cast<NXObject*>(obj);
        if (nxObj != NULL)
            moveBuilder->ObjectToMoveObject()->Add(nxObj);
    }

    Matrix4x4 xformMat;
    xformMat.Rxx = 1.0; xformMat.Rxy = 0.0; xformMat.Rxz = 0.0; xformMat.Xt = vec.X;
    xformMat.Ryx = 0.0; xformMat.Ryy = 1.0; xformMat.Ryz = 0.0; xformMat.Yt = vec.Y;
    xformMat.Rzx = 0.0; xformMat.Rzy = 0.0; xformMat.Rzz = 1.0; xformMat.Zt = vec.Z;

    Features::MoveObjectBuilder::MoveObjectResultOptions resultOpt =
        (m_actionMode == 1)
        ? Features::MoveObjectBuilder::MoveObjectResultOptionsMoveOriginal
        : Features::MoveObjectBuilder::MoveObjectResultOptionsCopyOriginal;

    moveBuilder->SetMoveObjectResult(resultOpt);
    moveBuilder->TransformMotion()->SetOption(GeometricUtilities::ModlMotion::OptionsNone);
    moveBuilder->SetPreMultiplicationTransform(xformMat);

    Session::UndoMarkId markId = theSession->SetUndoMark(Session::MarkVisibilityVisible, "dotmove_copy");
    moveBuilder->Commit();
    moveBuilder->Destroy();
    theSession->UpdateManager()->DoUpdate(markId);
    return true;
}

//------------------------------------------------------------------------------
// Callback: update_cb
//------------------------------------------------------------------------------
int dotmove_copy::update_cb(NXOpen::BlockStyler::UIBlock* block)
{
    try
    {
        if (block == move_button)
        {
            m_actionMode = 1;
        }
        else if (block == copy_button)
        {
            m_actionMode = 2;
        }
    }
    catch(exception& ex)
    {
        theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
// Callback: apply_cb
//------------------------------------------------------------------------------
int dotmove_copy::apply_cb()
{
    int errorCode = 0;
    try
    {
        if (m_actionMode == 0)
        {
            theUI->NXMessageBox()->Show("dotmove_copy", NXOpen::NXMessageBox::DialogTypeError,
                "Please click Move or Copy button first!");
            return 1;
        }
        if (!executeTransform())
            errorCode = 1;
        m_actionMode = 0;
    }
    catch(exception& ex)
    {
        errorCode = 1;
        theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
// Callback: ok_cb
//------------------------------------------------------------------------------
int dotmove_copy::ok_cb()
{
    int errorCode = 0;
    try
    {
        errorCode = apply_cb();
    }
    catch(exception& ex)
    {
        errorCode = 1;
        theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

PropertyList* dotmove_copy::GetBlockProperties(const char *blockID)
{
    return theDialog->GetBlockProperties(blockID);
}

extern "C" DllExport int ufusr_ask_unload()
{
    return (int)NXOpen::Session::LibraryUnloadOptionImmediately;
}