//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  S:\visiable\coaicad\Application\dotmove_copy.cpp
//
//        This file was generated by the NX Block UI Styler
//        Created by: pettycc
//              Version: NX 2306
//              Date: 07-15-2026  (Format: mm-dd-yyyy)
//              Time: 14:55 (Format: hh-mm)
//
//==============================================================================

#include "dotmove_copy.hpp"
#include <NXOpen/BasePart.hxx>
#include <NXOpen/Update.hxx>

using namespace NXOpen;
using namespace NXOpen::BlockStyler;

Session *(dotmove_copy::theSession) = NULL;
UI *(dotmove_copy::theUI) = NULL;

dotmove_copy::dotmove_copy()
{
    try
    {
        dotmove_copy::theSession = NXOpen::Session::GetSession();
        dotmove_copy::theUI = UI::GetUI();
        theDlxFileName = "dotmove_copy.dlx";
        theDialog = dotmove_copy::theUI->CreateDialog(theDlxFileName);
        theDialog->AddApplyHandler(make_callback(this, &dotmove_copy::apply_cb));
        theDialog->AddOkHandler(make_callback(this, &dotmove_copy::ok_cb));
        theDialog->AddUpdateHandler(make_callback(this, &dotmove_copy::update_cb));
        theDialog->AddInitializeHandler(make_callback(this, &dotmove_copy::initialize_cb));
        theDialog->AddDialogShownHandler(make_callback(this, &dotmove_copy::dialogShown_cb));
    }
    catch(exception& ex)
    {
        throw;
    }
}

dotmove_copy::~dotmove_copy()
{
    if (theDialog != NULL)
    {
        delete theDialog;
        theDialog = NULL;
    }
}

extern "C" DllExport void  ufusr(char *param, int *retcod, int param_len)
{
    dotmove_copy *thedotmove_copy = NULL;
    try
    {
        thedotmove_copy = new dotmove_copy();
        thedotmove_copy->Launch();
    }
    catch(exception& ex)
    {
        dotmove_copy::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    if(thedotmove_copy != NULL)
    {
        delete thedotmove_copy;
        thedotmove_copy = NULL;
    }
    return;
}

void dotmove_copy::Launch()
{
    try
    {
        theDialog->Show();
    }
    catch(exception& ex)
    {
        dotmove_copy::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

void dotmove_copy::initialize_cb()
{
    try
    {
        m_actionMode = 0;
        group0 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group0"));
        move_button = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("move_button"));
        copy_button = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("copy_button"));
        group1 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group1"));
        selection0 = dynamic_cast<NXOpen::BlockStyler::SelectObject*>(theDialog->TopBlock()->FindBlock("selection0"));
        group2 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group2"));
        startpoint = dynamic_cast<NXOpen::BlockStyler::SpecifyPoint*>(theDialog->TopBlock()->FindBlock("startpoint"));
        start_enum = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("start_enum"));
        group = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group"));
        endpoint = dynamic_cast<NXOpen::BlockStyler::SpecifyPoint*>(theDialog->TopBlock()->FindBlock("endpoint"));
        end_enum = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("end_enum"));
    }
    catch(exception& ex)
    {
        dotmove_copy::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

void dotmove_copy::dialogShown_cb()
{
    try
    {
    }
    catch(exception& ex)
    {
        dotmove_copy::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
// Helper: Get point coordinates from SpecifyPoint
//------------------------------------------------------------------------------
static Point3d GetPointFromSpecifyPoint(NXOpen::BlockStyler::SpecifyPoint* sp)
{
    Point3d pt = {0.0, 0.0, 0.0};
    if (sp == NULL) return pt;
    try
    {
        PropertyList* props = sp->GetProperties();
        pt = props->GetPoint("Point");
        delete props;
    }
    catch(...) { }
    return pt;
}

//------------------------------------------------------------------------------
// Helper: Get selected objects from SelectObject
//------------------------------------------------------------------------------
static std::vector<TaggedObject*> GetSelectedObjects(NXOpen::BlockStyler::SelectObject* sel)
{
    std::vector<TaggedObject*> objects;
    if (sel == NULL) return objects;
    try
    {
        PropertyList* props = sel->GetProperties();
        try
        {
            std::vector<NXOpen::TaggedObject*> selObjs = props->GetTaggedObjectVector("SelectedObjects");
            objects.assign(selObjs.begin(), selObjs.end());
        }
        catch(...)
        {
            TaggedObject* obj = props->GetTaggedObject("SelectedObject");
            if (obj != NULL) objects.push_back(obj);
        }
        delete props;
    }
    catch(...) { }
    return objects;
}

//------------------------------------------------------------------------------
// Execute MoveObjectBuilder with given objects, matrix, and result option
//------------------------------------------------------------------------------
static int ExecuteTransform(
    NXOpen::Features::MoveObjectBuilder* builder,
    const Matrix4x4& mat,
    Features::MoveObjectBuilder::MoveObjectResultOptions resultOpt)
{
    builder->SetMoveObjectResult(resultOpt);
    builder->TransformMotion()->SetOption(GeometricUtilities::ModlMotion::OptionsNone);
    builder->SetPreMultiplicationTransform(mat);
    Session* sess = Session::GetSession();
    Session::UndoMarkId markId = sess->SetUndoMark(Session::MarkVisibilityVisible, "Transform");
    builder->Commit();
    builder->Destroy();
    sess->UpdateManager()->DoUpdate(markId);
    return 0;
}

//------------------------------------------------------------------------------
// Core: Move objects
//------------------------------------------------------------------------------
int dotmove_copy::move_objects()
{
    Point3d startPt = GetPointFromSpecifyPoint(startpoint);
    Point3d endPt = GetPointFromSpecifyPoint(endpoint);

    Vector3d vec;
    vec.X = endPt.X - startPt.X;
    vec.Y = endPt.Y - startPt.Y;
    vec.Z = endPt.Z - startPt.Z;

    if (fabs(vec.X) < 0.0001 && fabs(vec.Y) < 0.0001 && fabs(vec.Z) < 0.0001)
    {
        dotmove_copy::theUI->NXMessageBox()->Show("dotmove_copy", NXOpen::NXMessageBox::DialogTypeWarning, 
            "Start point and end point are identical!");
        return 1;
    }

    std::vector<TaggedObject*> selObjects = GetSelectedObjects(selection0);
    if (selObjects.empty())
    {
        dotmove_copy::theUI->NXMessageBox()->Show("dotmove_copy", NXOpen::NXMessageBox::DialogTypeError, 
            "Please select objects to move!");
        return 1;
    }

    Part* workPart = theSession->Parts()->Work();
    Features::MoveObjectBuilder* moveBuilder = workPart->BaseFeatures()->CreateMoveObjectBuilder(NULL);

    for (TaggedObject* obj : selObjects)
    {
        NXObject* nxObj = dynamic_cast<NXObject*>(obj);
        if (nxObj != NULL)
        {
            moveBuilder->ObjectToMoveObject()->Add(nxObj);
        }
    }

    Matrix4x4 xformMat;
    xformMat.Rxx = 1.0; xformMat.Rxy = 0.0; xformMat.Rxz = 0.0; xformMat.Xt = vec.X;
    xformMat.Ryx = 0.0; xformMat.Ryy = 1.0; xformMat.Ryz = 0.0; xformMat.Yt = vec.Y;
    xformMat.Rzx = 0.0; xformMat.Rzy = 0.0; xformMat.Rzz = 1.0; xformMat.Zt = vec.Z;

    return ExecuteTransform(moveBuilder, xformMat, 
        Features::MoveObjectBuilder::MoveObjectResultOptionsMoveOriginal);
}

//------------------------------------------------------------------------------
// Core: Copy objects
//------------------------------------------------------------------------------
int dotmove_copy::copy_objects()
{
    Point3d startPt = GetPointFromSpecifyPoint(startpoint);
    Point3d endPt = GetPointFromSpecifyPoint(endpoint);

    Vector3d vec;
    vec.X = endPt.X - startPt.X;
    vec.Y = endPt.Y - startPt.Y;
    vec.Z = endPt.Z - startPt.Z;

    if (fabs(vec.X) < 0.0001 && fabs(vec.Y) < 0.0001 && fabs(vec.Z) < 0.0001)
    {
        dotmove_copy::theUI->NXMessageBox()->Show("dotmove_copy", NXOpen::NXMessageBox::DialogTypeError, 
            "Start point and end point are identical!");
        return 1;
    }

    std::vector<TaggedObject*> selObjects = GetSelectedObjects(selection0);
    if (selObjects.empty())
    {
        dotmove_copy::theUI->NXMessageBox()->Show("dotmove_copy", NXOpen::NXMessageBox::DialogTypeError, 
            "Please select objects to copy!");
        return 1;
    }

    Part* workPart = theSession->Parts()->Work();
    Features::MoveObjectBuilder* moveBuilder = workPart->BaseFeatures()->CreateMoveObjectBuilder(NULL);

    for (TaggedObject* obj : selObjects)
    {
        NXObject* nxObj = dynamic_cast<NXObject*>(obj);
        if (nxObj != NULL)
        {
            moveBuilder->ObjectToMoveObject()->Add(nxObj);
        }
    }

    Matrix4x4 xformMat;
    xformMat.Rxx = 1.0; xformMat.Rxy = 0.0; xformMat.Rxz = 0.0; xformMat.Xt = vec.X;
    xformMat.Ryx = 0.0; xformMat.Ryy = 1.0; xformMat.Ryz = 0.0; xformMat.Yt = vec.Y;
    xformMat.Rzx = 0.0; xformMat.Rzy = 0.0; xformMat.Rzz = 1.0; xformMat.Zt = vec.Z;

    return ExecuteTransform(moveBuilder, xformMat, 
        Features::MoveObjectBuilder::MoveObjectResultOptionsCopyOriginal);
}

//------------------------------------------------------------------------------
//Callback Name: apply_cb
//------------------------------------------------------------------------------
int dotmove_copy::apply_cb()
{
    int errorCode = 0;
    try
    {
        if (m_actionMode == 1)
            errorCode = move_objects();
        else if (m_actionMode == 2)
            errorCode = copy_objects();
        else
        {
            dotmove_copy::theUI->NXMessageBox()->Show("dotmove_copy", NXOpen::NXMessageBox::DialogTypeError, 
                "Please click 'Move' or 'Copy' button first!");
            errorCode = 1;
        }
        m_actionMode = 0;
    }
    catch(exception& ex)
    {
        errorCode = 1;
        dotmove_copy::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Callback Name: update_cb
//------------------------------------------------------------------------------
int dotmove_copy::update_cb(NXOpen::BlockStyler::UIBlock* block)
{
    try
    {
        if(block == move_button)
        {
            m_actionMode = 1;
            dotmove_copy::theUI->NXMessageBox()->Show("dotmove_copy", NXOpen::NXMessageBox::DialogTypeInformation, 
                "Move mode selected. Click Apply to execute.");
        }
        else if(block == copy_button)
        {
            m_actionMode = 2;
            dotmove_copy::theUI->NXMessageBox()->Show("dotmove_copy", NXOpen::NXMessageBox::DialogTypeInformation, 
                "Copy mode selected. Click Apply to execute.");
        }
    }
    catch(exception& ex)
    {
        dotmove_copy::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//Callback Name: ok_cb
//------------------------------------------------------------------------------
int dotmove_copy::ok_cb()
{
    int errorCode = 0;
    try
    {
        errorCode = apply_cb();
    }
    catch(exception& ex)
    {
        errorCode = 1;
        dotmove_copy::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Function Name: GetBlockProperties
//------------------------------------------------------------------------------
PropertyList* dotmove_copy::GetBlockProperties(const char *blockID)
{
    return theDialog->GetBlockProperties(blockID);
}

