//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  D:\nxfile\Application\BlockStyler777.cpp
//
//        This file was generated by the NX Block UI Styler
//        Created by: Az202
//              Version: NX 2306
//              Date: 07-16-2026  (Format: mm-dd-yyyy)
//              Time: 15:18 (Format: hh-mm)
//
//==============================================================================


//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include "BlockStyler777.hpp"
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

//------------------------------------------------------------------------------
// Initialize static variables
//------------------------------------------------------------------------------
Session *(BlockStyler777::theSession) = NULL;
UI *(BlockStyler777::theUI) = NULL;
//------------------------------------------------------------------------------
// Constructor for NX Styler class
//------------------------------------------------------------------------------
BlockStyler777::BlockStyler777()
{
    try
    {
        // Initialize the NX Open C++ API environment
        BlockStyler777::theSession = NXOpen::Session::GetSession();
        BlockStyler777::theUI = UI::GetUI();
        theDlxFileName = "777.dlx";
        theUserDefinedUIBlock = BlockStyler777::theUI->CreateDialog(theDlxFileName);
        // Registration of callback functions
        theUserDefinedUIBlock->AddUpdateHandler(make_callback(this, &BlockStyler777::update_cb));
        theUserDefinedUIBlock->AddInitializeHandler(make_callback(this, &BlockStyler777::initialize_cb));
        theUserDefinedUIBlock->AddDialogShownHandler(make_callback(this, &BlockStyler777::dialogShown_cb));
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        throw;
    }
}

//------------------------------------------------------------------------------
// Destructor for NX Styler class
//------------------------------------------------------------------------------
BlockStyler777::~BlockStyler777()
{
    if (theUserDefinedUIBlock != NULL)
    {
        delete theUserDefinedUIBlock;
        theUserDefinedUIBlock = NULL;
    }
}
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//---------------------Block UI Styler Callback Functions--------------------------
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//Callback Name: initialize_cb
//------------------------------------------------------------------------------
void BlockStyler777::initialize_cb()
{
    try
    {
        group = dynamic_cast<NXOpen::BlockStyler::Group*>(theUserDefinedUIBlock->TopBlock()->FindBlock("group"));
        movebutton = dynamic_cast<NXOpen::BlockStyler::Button*>(theUserDefinedUIBlock->TopBlock()->FindBlock("movebutton"));
        copybutton = dynamic_cast<NXOpen::BlockStyler::Button*>(theUserDefinedUIBlock->TopBlock()->FindBlock("copybutton"));
        group1 = dynamic_cast<NXOpen::BlockStyler::Group*>(theUserDefinedUIBlock->TopBlock()->FindBlock("group1"));
        selection0 = dynamic_cast<NXOpen::BlockStyler::SelectObject*>(theUserDefinedUIBlock->TopBlock()->FindBlock("selection0"));
        group2 = dynamic_cast<NXOpen::BlockStyler::Group*>(theUserDefinedUIBlock->TopBlock()->FindBlock("group2"));
        point0 = dynamic_cast<NXOpen::BlockStyler::SpecifyPoint*>(theUserDefinedUIBlock->TopBlock()->FindBlock("point0"));
        enum01 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theUserDefinedUIBlock->TopBlock()->FindBlock("enum01"));
        group3 = dynamic_cast<NXOpen::BlockStyler::Group*>(theUserDefinedUIBlock->TopBlock()->FindBlock("group3"));
        point01 = dynamic_cast<NXOpen::BlockStyler::SpecifyPoint*>(theUserDefinedUIBlock->TopBlock()->FindBlock("point01"));
        enum0 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theUserDefinedUIBlock->TopBlock()->FindBlock("enum0"));
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        BlockStyler777::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: dialogShown_cb
//This callback is executed just before the dialog launch. Thus any value set 
//here will take precedence and dialog will be launched showing that value. 
//------------------------------------------------------------------------------
void BlockStyler777::dialogShown_cb()
{
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        BlockStyler777::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: update_cb
//------------------------------------------------------------------------------
int BlockStyler777::update_cb(NXOpen::BlockStyler::UIBlock* block)
{
    try
    {
        if(block == movebutton)
        {
        //---------Enter your code here-----------
        }
        else if(block == copybutton)
        {
        //---------Enter your code here-----------
        }
        else if(block == selection0)
        {
        //---------Enter your code here-----------
        }
        else if(block == point0)
        {
        //---------Enter your code here-----------
        }
        else if(block == enum01)
        {
        //---------Enter your code here-----------
        }
        else if(block == point01)
        {
        //---------Enter your code here-----------
        }
        else if(block == enum0)
        {
        //---------Enter your code here-----------
        }
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        BlockStyler777::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//Function Name: RegisterUserDefinedUIBlock
//Description: Registers itself to the dialog which contains this block
//------------------------------------------------------------------------------
BlockStyler777* BlockStyler777::RegisterUserDefinedUIBlock(NXOpen::BlockStyler::BlockDialog* parentDialog, const char* blockID)
{
    BlockStyler777* theBlockStyler777 = new BlockStyler777();
    parentDialog->RegisterUserDefinedUIBlock(theBlockStyler777->theUserDefinedUIBlock, blockID);
    return theBlockStyler777;
}

//------------------------------------------------------------------------------
//Function Name: GetTopBlock
//Function returning TopBlock
//------------------------------------------------------------------------------
NXOpen::BlockStyler::CompositeBlock* BlockStyler777::GetTopBlock()
{
    if(theUserDefinedUIBlock != NULL)
    {
        return theUserDefinedUIBlock->TopBlock();
    }
    else
    {
        return NULL;
    }
}
