//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  D:\nxfile\Application\BlockStyler777.cs
//
//        This file was generated by the NX Block UI Styler
//        Created by: Az202
//              Version: NX 2306
//              Date: 07-15-2026  (Format: mm-dd-yyyy)
//              Time: 10:55 (Format: hh-mm)
//
//==============================================================================


//------------------------------------------------------------------------------
//These imports are needed for the following template code
//------------------------------------------------------------------------------
using System;
using NXOpen;
using NXOpen.BlockStyler;

//------------------------------------------------------------------------------
//Represents Block Styler application class
//------------------------------------------------------------------------------
public class BlockStyler777
{
    //class members
    private static Session theSession = null;
    private static UI theUI = null;
    private string theDlxFileName;
    private NXOpen.BlockStyler.BlockDialog theUserDefinedUIBlock;
    private NXOpen.BlockStyler.Group group;// Block type: Group
    private NXOpen.BlockStyler.Button movebutton;// Block type: Button
    private NXOpen.BlockStyler.Button copybutton;// Block type: Button
    private NXOpen.BlockStyler.Group group1;// Block type: Group
    private NXOpen.BlockStyler.SelectObject selection0;// Block type: Selection
    private NXOpen.BlockStyler.Group group2;// Block type: Group
    private NXOpen.BlockStyler.SpecifyPoint point0;// Block type: Specify Point
    private NXOpen.BlockStyler.Enumeration enum01;// Block type: Enumeration
    private NXOpen.BlockStyler.Group group3;// Block type: Group
    private NXOpen.BlockStyler.SpecifyPoint point01;// Block type: Specify Point
    private NXOpen.BlockStyler.Enumeration enum0;// Block type: Enumeration
    //------------------------------------------------------------------------------
    //Bit Option for Property: SnapPointTypesEnabled
    //------------------------------------------------------------------------------
    public static readonly int              SnapPointTypesEnabled_UserDefined = (1 << 0);
    public static readonly int                 SnapPointTypesEnabled_Inferred = (1 << 1);
    public static readonly int           SnapPointTypesEnabled_ScreenPosition = (1 << 2);
    public static readonly int                 SnapPointTypesEnabled_EndPoint = (1 << 3);
    public static readonly int                 SnapPointTypesEnabled_MidPoint = (1 << 4);
    public static readonly int             SnapPointTypesEnabled_ControlPoint = (1 << 5);
    public static readonly int             SnapPointTypesEnabled_Intersection = (1 << 6);
    public static readonly int                SnapPointTypesEnabled_ArcCenter = (1 << 7);
    public static readonly int            SnapPointTypesEnabled_QuadrantPoint = (1 << 8);
    public static readonly int            SnapPointTypesEnabled_ExistingPoint = (1 << 9);
    public static readonly int             SnapPointTypesEnabled_PointonCurve = (1 <<10);
    public static readonly int           SnapPointTypesEnabled_PointonSurface = (1 <<11);
    public static readonly int         SnapPointTypesEnabled_PointConstructor = (1 <<12);
    public static readonly int     SnapPointTypesEnabled_TwocurveIntersection = (1 <<13);
    public static readonly int             SnapPointTypesEnabled_TangentPoint = (1 <<14);
    public static readonly int                    SnapPointTypesEnabled_Poles = (1 <<15);
    public static readonly int         SnapPointTypesEnabled_BoundedGridPoint = (1 <<16);
    public static readonly int         SnapPointTypesEnabled_FacetVertexPoint = (1 <<17);
    public static readonly int            SnapPointTypesEnabled_DefiningPoint = (1 <<18);
    //------------------------------------------------------------------------------
    //Bit Option for Property: SnapPointTypesOnByDefault
    //------------------------------------------------------------------------------
    public static readonly int             SnapPointTypesOnByDefault_EndPoint = (1 << 3);
    public static readonly int             SnapPointTypesOnByDefault_MidPoint = (1 << 4);
    public static readonly int         SnapPointTypesOnByDefault_ControlPoint = (1 << 5);
    public static readonly int         SnapPointTypesOnByDefault_Intersection = (1 << 6);
    public static readonly int            SnapPointTypesOnByDefault_ArcCenter = (1 << 7);
    public static readonly int        SnapPointTypesOnByDefault_QuadrantPoint = (1 << 8);
    public static readonly int        SnapPointTypesOnByDefault_ExistingPoint = (1 << 9);
    public static readonly int         SnapPointTypesOnByDefault_PointonCurve = (1 <<10);
    public static readonly int       SnapPointTypesOnByDefault_PointonSurface = (1 <<11);
    public static readonly int     SnapPointTypesOnByDefault_PointConstructor = (1 <<12);
    public static readonly int     SnapPointTypesOnByDefault_BoundedGridPoint = (1 <<16);
    public static readonly int     SnapPointTypesOnByDefault_FacetVertexPoint = (1 <<17);
    //------------------------------------------------------------------------------
    //Bit Option for Property: SnapPointTypesOnByDefault
    //------------------------------------------------------------------------------
    public static readonly int          SnapPointTypesOnByDefault_UserDefined = (1 << 0);
    public static readonly int             SnapPointTypesOnByDefault_Inferred = (1 << 1);
    public static readonly int       SnapPointTypesOnByDefault_ScreenPosition = (1 << 2);
    public static readonly int SnapPointTypesOnByDefault_TwocurveIntersection = (1 <<13);
    public static readonly int         SnapPointTypesOnByDefault_TangentPoint = (1 <<14);
    public static readonly int                SnapPointTypesOnByDefault_Poles = (1 <<15);
    public static readonly int        SnapPointTypesOnByDefault_DefiningPoint = (1 <<18);
    
    //------------------------------------------------------------------------------
    //Constructor for NX Styler class
    //------------------------------------------------------------------------------
    public BlockStyler777()
    {
        try
        {
            theSession = Session.GetSession();
            theUI = UI.GetUI();
            theDlxFileName = "777.dlx";
            theUserDefinedUIBlock = theUI.CreateDialog(theDlxFileName);
            theUserDefinedUIBlock.AddUpdateHandler(new NXOpen.BlockStyler.BlockDialog.Update(update_cb));
            theUserDefinedUIBlock.AddInitializeHandler(new NXOpen.BlockStyler.BlockDialog.Initialize(initialize_cb));
            theUserDefinedUIBlock.AddDialogShownHandler(new NXOpen.BlockStyler.BlockDialog.DialogShown(dialogShown_cb));
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            throw ex;
        }
    }
    //------------------------------------------------------------------------------
    
    //------------------------------------------------------------------------------
    //Method Name: Dispose
    //------------------------------------------------------------------------------
    public void Dispose()
    {
        if(theUserDefinedUIBlock != null)
        {
            theUserDefinedUIBlock.Dispose();
            theUserDefinedUIBlock = null;
        }
    }
    
    //------------------------------------------------------------------------------
    //---------------------Block UI Styler Callback Functions--------------------------
    //------------------------------------------------------------------------------
    
    //------------------------------------------------------------------------------
    //Callback Name: initialize_cb
    //------------------------------------------------------------------------------
    public void initialize_cb()
    {
        try
        {
            group = (NXOpen.BlockStyler.Group)theUserDefinedUIBlock.TopBlock.FindBlock("group");
            movebutton = (NXOpen.BlockStyler.Button)theUserDefinedUIBlock.TopBlock.FindBlock("movebutton");
            copybutton = (NXOpen.BlockStyler.Button)theUserDefinedUIBlock.TopBlock.FindBlock("copybutton");
            group1 = (NXOpen.BlockStyler.Group)theUserDefinedUIBlock.TopBlock.FindBlock("group1");
            selection0 = (NXOpen.BlockStyler.SelectObject)theUserDefinedUIBlock.TopBlock.FindBlock("selection0");
            group2 = (NXOpen.BlockStyler.Group)theUserDefinedUIBlock.TopBlock.FindBlock("group2");
            point0 = (NXOpen.BlockStyler.SpecifyPoint)theUserDefinedUIBlock.TopBlock.FindBlock("point0");
            enum01 = (NXOpen.BlockStyler.Enumeration)theUserDefinedUIBlock.TopBlock.FindBlock("enum01");
            group3 = (NXOpen.BlockStyler.Group)theUserDefinedUIBlock.TopBlock.FindBlock("group3");
            point01 = (NXOpen.BlockStyler.SpecifyPoint)theUserDefinedUIBlock.TopBlock.FindBlock("point01");
            enum0 = (NXOpen.BlockStyler.Enumeration)theUserDefinedUIBlock.TopBlock.FindBlock("enum0");
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: dialogShown_cb
    //This callback is executed just before the dialog launch. Thus any value set 
    //here will take precedence and dialog will be launched showing that value. 
    //------------------------------------------------------------------------------
    public void dialogShown_cb()
    {
        try
        {
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: update_cb
    //------------------------------------------------------------------------------
    public int update_cb( NXOpen.BlockStyler.UIBlock block)
    {
        try
        {
            if(block == movebutton)
            {
            //---------Enter your code here-----------
            }
            else if(block == copybutton)
            {
            //---------Enter your code here-----------
            }
            else if(block == selection0)
            {
            //---------Enter your code here-----------
            }
            else if(block == point0)
            {
            //---------Enter your code here-----------
            }
            else if(block == enum01)
            {
            //---------Enter your code here-----------
            }
            else if(block == point01)
            {
            //---------Enter your code here-----------
            }
            else if(block == enum0)
            {
            //---------Enter your code here-----------
            }
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return 0;
    }
    
    //------------------------------------------------------------------------------
    //Function Name: RegisterUserDefinedUIBlock
    //Registers itself to the dialog which contains this block
    //------------------------------------------------------------------------------
    public static BlockStyler777 RegisterUserDefinedUIBlock(NXOpen.BlockStyler.BlockDialog parentDialog, string blockID)
    {
        BlockStyler777 theBlockStyler777 = new BlockStyler777();
        parentDialog.RegisterUserDefinedUIBlock(theBlockStyler777.theUserDefinedUIBlock, blockID);
        return theBlockStyler777;
    }
    
    //------------------------------------------------------------------------------
    //Property Name: TopBlock
    //ReadOnly property to give access to TopBlock
    //------------------------------------------------------------------------------
    public NXOpen.BlockStyler.CompositeBlock TopBlock
    {
        get
        {
            if (theUserDefinedUIBlock != null)
            {
                return theUserDefinedUIBlock.TopBlock;
            }
            else
            {
                return null;
            }
        }
    }
    
}
