//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  D:\nxfile\Application\qq77.cpp
//
//        This file was generated by the NX Block UI Styler
//        Created by: Administrator
//              Version: NX 2306
//              Date: 07-15-2026  (Format: mm-dd-yyyy)
//              Time: 10:45 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C++ source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include "qq77.hpp"
#include <NXOpen/NXObject.hxx>
#include <NXOpen/Features_MoveObjectBuilder.hxx>
#include <NXOpen/GeometricUtilities_ModlMotion.hxx>
#include <NXOpen/SelectNXObjectList.hxx>
#include <NXOpen/Part.hxx>
#include <NXOpen/PartCollection.hxx>
#include <NXOpen/DirectionCollection.hxx>
#include <NXOpen/UnitCollection.hxx>
#include <NXOpen/ScCollectorCollection.hxx>
#include <NXOpen/BodyDumbRule.hxx>
#include <NXOpen/ScRuleFactory.hxx>
#include <NXOpen/ScCollector.hxx>
#include <NXOpen/Body.hxx>
#include <NXOpen/DisplayableObject.hxx>
#include <NXOpen/MeasureRectangularExtreme.hxx>
#include <NXOpen/Features_BaseFeatureCollection.hxx>
#include <NXOpen/WCS.hxx>
#include <cmath>
 #include <uf_modl_utilities.h>
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

//------------------------------------------------------------------------------
// Initialize static variables
//------------------------------------------------------------------------------
Session *(qq77::theSession) = NULL;
UI *(qq77::theUI) = NULL;
//------------------------------------------------------------------------------
// Constructor for NX Styler class
//------------------------------------------------------------------------------
qq77::qq77()
{
    try
    {
        // Initialize the NX Open C++ API environment
        qq77::theSession = NXOpen::Session::GetSession();
        qq77::theUI = UI::GetUI();
        theDlxFileName = "qq77.dlx";
        theDialog = qq77::theUI->CreateDialog(theDlxFileName);
        // Registration of callback functions
        theDialog->AddApplyHandler(make_callback(this, &qq77::apply_cb));
        theDialog->AddOkHandler(make_callback(this, &qq77::ok_cb));
        theDialog->AddUpdateHandler(make_callback(this, &qq77::update_cb));
        theDialog->AddInitializeHandler(make_callback(this, &qq77::initialize_cb));
        theDialog->AddDialogShownHandler(make_callback(this, &qq77::dialogShown_cb));
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        throw;
    }
}

//------------------------------------------------------------------------------
// Destructor for NX Styler class
//------------------------------------------------------------------------------
qq77::~qq77()
{
    if (theDialog != NULL)
    {
        delete theDialog;
        theDialog = NULL;
    }
}
//------------------------------- DIALOG LAUNCHING ---------------------------------
//
//    Before invoking this application one needs to open any part/empty part in NX
//    because of the behavior of the blocks.
//
//    Make sure the dlx file is in one of the following locations:
//        1.) From where NX session is launched
//        2.) $UGII_USER_DIR/application
//        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
//            recommended. This variable is set to a full directory path to a file 
//            containing a list of root directories for all custom applications.
//            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
//
//    You can create the dialog using one of the following way:
//
//    1. USER EXIT
//
//        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
//        2) Invoke the Shared Library through File->Execute->NX Open menu.
//
//------------------------------------------------------------------------------
extern "C" DllExport void  ufusr(char *param, int *retcod, int param_len)
{
    qq77 *theqq77 = NULL;
    *retcod = 0;
    try
    {
        theqq77 = new qq77();
        // The following method shows the dialog immediately
        theqq77->Launch();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        *retcod = 1;
        qq77::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    if(theqq77 != NULL)
    {
        delete theqq77;
        theqq77 = NULL;
    }
}

//------------------------------------------------------------------------------
// This method specifies how a shared image is unloaded from memory
// within NX. This method gives you the capability to unload an
// internal NX Open application or user  exit from NX. Specify any
// one of the three constants as a return value to determine the type
// of unload to perform:
//
//
//    Immediately : unload the library as soon as the automation program has completed
//    Explicitly  : unload the library from the "Unload Shared Image" dialog
//    AtTermination : unload the library when the NX session terminates
//
//
// NOTE:  A program which associates NX Open applications with the menubar
// MUST NOT use this option since it will UNLOAD your NX Open application image
// from the menubar.
//------------------------------------------------------------------------------
extern "C" DllExport int ufusr_ask_unload()
{
    //return (int)Session::LibraryUnloadOptionExplicitly;
    return (int)Session::LibraryUnloadOptionImmediately;
    //return (int)Session::LibraryUnloadOptionAtTermination;
}

//------------------------------------------------------------------------------
// Following method cleanup any housekeeping chores that may be needed.
// This method is automatically called by NX.
//------------------------------------------------------------------------------
extern "C" DllExport void ufusr_cleanup(void)
{
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        qq77::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//This method launches the dialog to screen
//------------------------------------------------------------------------------
NXOpen::BlockStyler::BlockDialog::DialogResponse qq77::Launch()
{
    NXOpen::BlockStyler::BlockDialog::DialogResponse dialogResponse= NXOpen::BlockStyler::BlockDialog::DialogResponse::DialogResponseInvalid;
    try
    {
        dialogResponse=theDialog->Launch();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        qq77::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return dialogResponse;
}

//------------------------------------------------------------------------------
//---------------------Block UI Styler Callback Functions--------------------------
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//Callback Name: initialize_cb
//------------------------------------------------------------------------------
void qq77::initialize_cb()
{
    try
    {
        group = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group"));
        button0 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button0"));
        button01 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button01"));
        group3 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group3"));
        selection0 = dynamic_cast<NXOpen::BlockStyler::SelectObject*>(theDialog->TopBlock()->FindBlock("selection0"));
        group2 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group2"));
        point0 = dynamic_cast<NXOpen::BlockStyler::SpecifyPoint*>(theDialog->TopBlock()->FindBlock("point0"));
        enum0 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum0"));
        group1 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group1"));
        point01 = dynamic_cast<NXOpen::BlockStyler::SpecifyPoint*>(theDialog->TopBlock()->FindBlock("point01"));
        enum01 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum01"));
        // 初始化模式
        m_selectedResult = 0;
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        qq77::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: dialogShown_cb
//This callback is executed just before the dialog launch. Thus any value set 
//here will take precedence and dialog will be launched showing that value. 
//------------------------------------------------------------------------------
void qq77::dialogShown_cb()
{
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        qq77::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: apply_cb
//------------------------------------------------------------------------------
int qq77::apply_cb()
{
    int errorCode = 0;
    try
    {
        Features::MoveObjectBuilder::MoveObjectResultOptions resultMode =
            (m_selectedResult == 0)
            ? Features::MoveObjectBuilder::MoveObjectResultOptionsMoveOriginal
            : Features::MoveObjectBuilder::MoveObjectResultOptionsCopyOriginal;

        errorCode = performTransform(resultMode);
    }
        catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        qq77::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Callback Name: update_cb
//------------------------------------------------------------------------------
int qq77::update_cb(NXOpen::BlockStyler::UIBlock* block)
{
    try
    {
             if(block == button0)
             {
                m_selectedResult = 0;
            }
             else if(block == button01)
             {
                m_selectedResult = 1;
            }
        else if(block == selection0)
        {
        //---------Enter your code here-----------
        }
        else if(block == point0)
        {
        //---------Enter your code here-----------
        }
        else if(block == enum0)
        {
        //---------Enter your code here-----------
        }
        else if(block == point01)
        {
        //---------Enter your code here-----------
        }
        else if(block == enum01)
        {
        //---------Enter your code here-----------
        }
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        qq77::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
// 执行移动或复制操作
//------------------------------------------------------------------------------
int qq77::performTransform(Features::MoveObjectBuilder::MoveObjectResultOptions mode)
{
    int errorCode = 0;
    try
    {
        Part* workPart = theSession->Parts()->Work();
        if (!workPart)
        {
            theUI->NXMessageBox()->Show("qq77", NXMessageBox::DialogTypeWarning,
                "请先打开一个部件");
            return 1;
        }

        // 获取选中的对象
        PropertyList* selProps = GetBlockProperties("selection0");
        std::vector<TaggedObject*> objects = selProps->GetTaggedObjectVector("SelectedObjects");
        delete selProps;

        if (objects.empty())
        {
            theUI->NXMessageBox()->Show("qq77", NXMessageBox::DialogTypeWarning,
                "请先选择要移动的对象");
            return 1;
        }

        // 获取起始点和结束点（可选，没选则默认 (0,0,0)）
        PropertyList* startProps = GetBlockProperties("point0");
        Point3d startPt(0,0,0);
        try { startPt = startProps->GetPoint("Point"); } catch (...) { }
        delete startProps;

        PropertyList* endProps = GetBlockProperties("point01");
        Point3d endPt(0,0,0);
        try { endPt = endProps->GetPoint("Point"); } catch (...) { }
        delete endProps;

        // 读取 enum0（起始点参考类型）
        PropertyList* e0Props = GetBlockProperties("enum0");
        int startRef = e0Props->GetEnum("Value");
        delete e0Props;
        // 读取 enum01（结束点参考类型）
        PropertyList* e1Props = GetBlockProperties("enum01");
        int endRef = e1Props->GetEnum("Value");
        delete e1Props;
        // 计算参考点
        Point3d refStart = startPt;
        Point3d refEnd = endPt;
        // ====== 计算体包围盒（如果 enum0 或 enum01 需要用到体测量）=======
        bool needBodyMeas = (startRef >= 0 && startRef <= 3) || (endRef == 2 || endRef == 3);
        bool bodyMeasOK = false;
        double cx = 0, cy = 0, cz = 0, maxZ = 0, minZ = 0;

        if (needBodyMeas) {
            for (TaggedObject* obj : objects) {
                Body* bodyObj = dynamic_cast<Body*>(obj);
                if (bodyObj) {
                    try {
                        double bbox[6];
                        int ret = UF_MODL_ask_bounding_box(bodyObj->Tag(), bbox);
                        if (ret == 0) {
                            cx = (bbox[0] + bbox[3]) * 0.5;
                            cy = (bbox[1] + bbox[4]) * 0.5;
                            cz = (bbox[2] + bbox[5]) * 0.5;
                            maxZ = bbox[5];
                            minZ = bbox[2];
                            bodyMeasOK = true;
                        } else {
                            theUI->NXMessageBox()->Show("qq77", NXMessageBox::DialogTypeWarning,
                                (std::string("体测量失败 (UFUN错误: ") + std::to_string(ret) + ")").c_str());
                        }
                    } catch (NXOpen::NXException& ex) {
                        std::string m = "体测量失败 错误码: " + std::to_string(ex.ErrorCode());
                        theUI->NXMessageBox()->Show("qq77", NXMessageBox::DialogTypeWarning, m.c_str());
                    }
                    break;
                }
            }
        }

        // ====== 计算起始点参考 ======
        // enum0: 体中心上(0), 体中心下(1), 体中心(2), 面中心(3)
        if (bodyMeasOK) {
            if (startRef == 0) refStart = Point3d(cx, cy, maxZ);
            else if (startRef == 1) refStart = Point3d(cx, cy, minZ);
            else if (startRef == 2) refStart = Point3d(cx, cy, cz);
            else if (startRef == 3) refStart = Point3d(cx, cy, cz);
        }

        // ====== 计算结束点参考 ======
        // enum01: ABS原点(0), WCS原点(1), 体中心(2), 面中心(3), XO点(4), YO点(5), ZO点(6)
        double ex = endPt.X, ey = endPt.Y, ez = endPt.Z;
        if (endRef == 0) { ex = 0; ey = 0; ez = 0; }
        else if (endRef == 1) {
            Point3d wcsOrg = workPart->WCS()->Origin();
            ex = wcsOrg.X; ey = wcsOrg.Y; ez = wcsOrg.Z;
        }
        else if (endRef == 2 && bodyMeasOK) { ex = cx; ey = cy; ez = cz; }
        else if (endRef == 3 && bodyMeasOK) { ex = cx; ey = cy; ez = cz; }
        else if (endRef == 4) { ey = 0; ez = 0; }
        else if (endRef == 5) { ex = 0; ez = 0; }
        else if (endRef == 6) { ex = 0; ey = 0; }

        // XO/YO/ZO 点用体中心坐标（如果测量成功）
        if (bodyMeasOK) {
            if (endRef == 4) { ex = cx; }
            else if (endRef == 5) { ey = cy; }
            else if (endRef == 6) { ez = cz; }
        }

        double dx = ex - refStart.X;
        double dy = ey - refStart.Y;
        double dz = ez - refStart.Z;

        // 检查位移量是否为零
        if (fabs(dx) < 0.001 && fabs(dy) < 0.001 && fabs(dz) < 0.001) {
            theUI->NXMessageBox()->Show("qq77", NXMessageBox::DialogTypeWarning, "位移量为零，请指定不同的起始点和结束点");
            return 1;
        }
        // 创建 MoveObjectBuilder（Features 命名空间）
        Features::MoveObjectBuilder* moveBuilder =
            workPart->BaseFeatures()->CreateMoveObjectBuilder(NULL);

        // 添加要移动的对象
        for (TaggedObject* obj : objects)
        {
            NXObject* nxObj = dynamic_cast<NXObject*>(obj);
            if (nxObj)
            {
                moveBuilder->ObjectToMoveObject()->Add(nxObj);
            }
        }

        // 设置 delta XYZ 位移（ModlMotion 引擎）
          // 设置 delta XYZ 位移
          GeometricUtilities::ModlMotion* motion = moveBuilder->TransformMotion();
          motion->SetOption(GeometricUtilities::ModlMotion::OptionsDeltaXyz);
          motion->SetDeltaEnum(GeometricUtilities::ModlMotion::DeltaReferenceWcsWorkPart);
          motion->DeltaXc()->SetValue(dx);
          motion->DeltaYc()->SetValue(dy);
          motion->DeltaZc()->SetValue(dz);
          moveBuilder->SetMoveObjectResult(mode);
          moveBuilder->Commit();
          moveBuilder->Destroy();
          const char* msg = (mode == Features::MoveObjectBuilder::MoveObjectResultOptionsCopyOriginal)
              ? "复制完成" : "移动完成";
          theUI->NXMessageBox()->Show("qq77", NXMessageBox::DialogTypeInformation, msg);
        }
    catch (exception& ex)
    {
        errorCode = 1;
        theUI->NXMessageBox()->Show("qq77", NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Callback Name: ok_cb
//------------------------------------------------------------------------------
int qq77::ok_cb()
{
    int errorCode = 0;
    try
    {
        errorCode = apply_cb();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        qq77::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Function Name: GetBlockProperties
//Description: Returns the propertylist of the specified BlockID
//------------------------------------------------------------------------------
PropertyList* qq77::GetBlockProperties(const char *blockID)
{
    return theDialog->GetBlockProperties(blockID);
}
