//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  以点选择移动与复制.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: Lttt
//              Version: NX 2306
//              Date: 07-15-2026
//              Time: 11:00
//
//==============================================================================

#ifndef 以点选择移动与复制_H_INCLUDED
#define 以点选择移动与复制_H_INCLUDED

#include <uf_defs.h>
#include <iostream>
#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include <NXOpen/BlockStyler_Group.hxx>
#include <NXOpen/BlockStyler_Button.hxx>
#include <NXOpen/BlockStyler_SelectObject.hxx>
#include <NXOpen/BlockStyler_SpecifyPoint.hxx>
#include <NXOpen/BlockStyler_Enumeration.hxx>

using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

class DllExport 以点选择移动与复制
{
public:
    static Session *theSession;
    static UI *theUI;
    以点选择移动与复制();
    ~以点选择移动与复制();
    NXOpen::BlockStyler::BlockDialog::DialogResponse Launch();

    void initialize_cb();
    void dialogShown_cb();
    int apply_cb();
    int ok_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    PropertyList* GetBlockProperties(const char *blockID);

private:
    const char* theDlxFileName;
    NXOpen::BlockStyler::BlockDialog* theDialog;

    // --- Block declarations (match the dlx design) ---
    NXOpen::BlockStyler::Group*          group0;
    NXOpen::BlockStyler::Button*         moveButton;     // 移动按钮
    NXOpen::BlockStyler::Button*         copyButton0;    // 复制按钮
    NXOpen::BlockStyler::Group*          group;
    NXOpen::BlockStyler::SelectObject*   selectObject;   // 选择实体/面
    NXOpen::BlockStyler::Group*          group1;
    NXOpen::BlockStyler::SpecifyPoint*   point0;         // 起始点坐标
    NXOpen::BlockStyler::Enumeration*    enum0;          // 起始点单选 (RadioBox)
    NXOpen::BlockStyler::Group*          group2;
    NXOpen::BlockStyler::SpecifyPoint*   point01;        // 结束点坐标
    NXOpen::BlockStyler::Enumeration*    enum01;         // 结束点单选 (RadioBox)

    bool m_isCopy;  // 当前模式: false=移动, true=复制
    bool m_fromModeButton; // true=这次Apply来自模式按钮, 不执行
    // bool m_pendingExec; // removed - no longer needed
};

#endif
